package com.example.accountservice.domain;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTypeConvertedEnum;

import java.io.Serializable;

@DynamoDBTable(tableName = "account")
public class Account implements Serializable {

    private static final long serialVersionUID = 8331074361667921244L;

    private String id;

    private AccountStatus status;

    private int balance;

    private String customerId;

    public Account() {
    }

    public Account(String customerId) {
        this.customerId = customerId;
    }

    public Account(String id, AccountStatus status, int balance, String customerId) {
        this.id = id;
        this.status = status;
        this.balance = balance;
        this.customerId = customerId;
    }

    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @DynamoDBAttribute(attributeName = "status")
    @DynamoDBTypeConvertedEnum
    public AccountStatus getStatus() {
        return status;
    }

    public void setStatus(AccountStatus status) {
        this.status = status;
    }

    @DynamoDBAttribute(attributeName = "balance")
    public int getBalance() {
        return balance;
    }

    public void setBalance(int balance) {
        this.balance = balance;
    }

    @DynamoDBIndexHashKey(
        attributeName = "customerId",
        globalSecondaryIndexName = "customerId-index"
    )
    public String getCustomerId() {
        return customerId;
    }

    public void setCustomerId(String customerId) {
        this.customerId = customerId;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }

        Account account = (Account) o;

        if (id != null ? !id.equals(account.id) : account.id != null) {
            return false;
        }
        return customerId != null ? customerId.equals(account.customerId) : account.customerId == null;
    }

    @Override
    public int hashCode() {
        int result = id != null ? id.hashCode() : 0;
        result = 31 * result + (customerId != null ? customerId.hashCode() : 0);
        return result;
    }

    @Override
    public String toString() {
        return "Account{" +
               "id='" + id + '\'' +
               ", status=" + status +
               ", balance=" + balance +
               ", customerId='" + customerId + '\'' +
               '}';
    }
}
