package com.example.orderservice.domain;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTypeConvertedEnum;

import java.io.Serializable;

@DynamoDBTable(tableName = "order")
public class Order implements Serializable {

    private static final long serialVersionUID = 8331074361667921244L;

    private String id;

    private String accountId;

    private int amount;

    private OrderStatus status;

    public Order() {
    }

    public Order(String id, String accountId, int amount, OrderStatus status) {
        this.id = id;
        this.accountId = accountId;
        this.amount = amount;
        this.status = status;
    }

    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @DynamoDBIndexHashKey(
        attributeName = "accountId",
        globalSecondaryIndexName = "accountId-index"
    )
    public String getAccountId() {
        return accountId;
    }

    public void setAccountId(String accountId) {
        this.accountId = accountId;
    }

    @DynamoDBAttribute(attributeName = "amount")
    public int getAmount() {
        return amount;
    }

    public void setAmount(int amount) {
        this.amount = amount;
    }

    @DynamoDBAttribute(attributeName = "status")
    @DynamoDBTypeConvertedEnum
    public OrderStatus getStatus() {
        return status;
    }

    public void setStatus(OrderStatus status) {
        this.status = status;
    }
}
